# Generated by Django 5.1.1 on 2024-09-30 16:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('artiste', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('realisateur', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Jeuxdeplateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('createur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('auteur', models.CharField(max_length=150)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(default=datetime.datetime(2024, 10, 7, 16, 9, 49, 86198, tzinfo=datetime.timezone.utc))),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.media')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.membre')),
            ],
        ),
    ]
