# Generated by Django 5.1.1 on 2024-10-01 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_cd_dvd_jeuxdeplateau_livre_membre_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 13, 48, 48, 43548, tzinfo=datetime.timezone.utc)),
        ),
    ]
