# Generated by Django 5.1.1 on 2024-10-01 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0006_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 17, 42, 24, 845209, tzinfo=datetime.timezone.utc)),
        ),
    ]
