# Generated by Django 5.1.1 on 2024-10-02 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0007_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeuxdeplateau',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jeuxdeplateau',
            name='nom',
        ),
        migrations.AddField(
            model_name='jeuxdeplateau',
            name='media_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 8, 52, 16, 538553, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jeuxdeplateau',
            name='createur',
            field=models.CharField(default='Créateur inconnu', max_length=150),
        ),
        migrations.AlterField(
            model_name='media',
            name='nom',
            field=models.CharField(default='Média par défaut', max_length=150),
        ),
    ]
