# Generated by Django 5.1.1 on 2024-10-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0008_remove_jeuxdeplateau_id_remove_jeuxdeplateau_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 16, 42, 34, 63716, tzinfo=datetime.timezone.utc)),
        ),
    ]
