# Generated by Django 5.1.1 on 2024-10-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0012_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='est_jeu_de_plateau',
            field=models.BooleanField(default=False),
        ),
    ]
